# This workflow is intended to deploy the webpage to gh-pages

name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
          # install dependencies
          npm install

          # serve with hot reload at localhost:8080
          npm run dev

          # build for production with minification, also build the search index
          npm run build

          # build the search index only
          npm run build-search

          # build for production and view the bundle analyzer report
          npm run build --report

          # run unit tests
          npm run unit

          # run e2e tests
          npm run e2e

          # run all tests
          npm test

          # deploy playbook to GH pages (includes build and deploy to GH pages)
          npm run gh-pages
